---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine/git
run:
  path: sh
  args: ['-xc', 'cd peatio-repository && git rev-parse --short=8 HEAD > ../tag/name']
inputs:
  - name: peatio-repository
outputs:
  - name: tag
