- id: 1
  code: icbc
  name: 工商银行
- id: 2
  code: cbc
  name: 建设银行
- id: 3
  code: bc
  name: 中国银行
- id: 4
  code: bcm
  name: 交通银行
- id: 5
  code: abc
  name: 农业银行
- id: 6
  code: cmb
  name: 招商银行
- id: 7
  code: cmbc
  name: 民生银行
- id: 8
  code: cncb
  name: 中信银行
- id: 9
  code: hxb
  name: 华夏银行
- id: 10
  code: cib
  name: 兴业银行
- id: 11
  code: spdb
  name: 浦东发展银行
- id: 12
  code: bob
  name: 北京银行
- id: 13
  code: ceb
  name: 光大银行
- id: 14
  code: sdb
  name: 深圳发展银行
- id: 15
  code: gdb
  name: 广东发展银行
