- id: satoshi
  code: 200
  currency: btc
  link: /deposits/coins/satoshi
  description: btc
  confirm: 1
  confirm_max: 6
  low: 0.1
  transfer: now
  latency: 10
- id: bank
  code: 400
  currency: cny
  link: /deposits/banks/new
  description: cny
  transfer: now
  latency: 10
  account_bank: '#Fake Bank Name#'
  account_holder: '#Fake Card Holder#'
  account_number: '#Fake Card Number#'
