apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  dbPassword: {{ default "" .Values.db.password }}
  rabbitmqPassword: {{ default "" .Values.rabbitmq.password }}
  redisPassword: {{ default "" .Values.redis.password }}
  {{- if .Values.cookiesSecretKey }}
  cookiesSecretKey: {{ .Values.cookiesSecretKey | b64enc | quote }}
  {{- else }}
  cookiesSecretKey: {{ randAlphaNum 128 | b64enc | quote }}
  {{- end }}
  {{- if .Values.jwtSharedSecretKey }}
  jwtSharedSecretKey: {{ .Values.jwtSharedSecretKey | b64enc | quote }}
  {{- else }}
  jwtSharedSecretKey: {{ randAlphaNum 2236 | b64enc | quote }}
  {{- end }}
